// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package apidoc is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Request
	Response
*/
package apidoc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product int32

const (
	Product_ProductUnknown Product = 0
	Product_ProductOne     Product = 1000
	Product_ProductTwo     Product = 1001
	Product_ProductThree   Product = 1002
)

var Product_name = map[int32]string{
	0:    "ProductUnknown",
	1000: "ProductOne",
	1001: "ProductTwo",
	1002: "ProductThree",
}
var Product_value = map[string]int32{
	"ProductUnknown": 0,
	"ProductOne":     1000,
	"ProductTwo":     1001,
	"ProductThree":   1002,
}

func (x Product) String() string {
	return proto.EnumName(Product_name, int32(x))
}
func (Product) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
	Req string `protobuf:"bytes,1,opt,name=req" json:"req,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type Response struct {
	Reply string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "apidoc.Request")
	proto.RegisterType((*Response)(nil), "apidoc.Response")
	proto.RegisterEnum("apidoc.Product", Product_name, Product_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	Say(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Say(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/apidoc.Hello/Say", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	Say(context.Context, *Request) (*Response, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apidoc.Hello/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Say(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apidoc.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Hello_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2c, 0xc8, 0x4c, 0xc9, 0x4f, 0x56,
	0x92, 0xe6, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0x4a,
	0x2d, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x14, 0xb8, 0x38, 0x82, 0x52,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0x8b, 0x52, 0x0b, 0x72, 0x2a, 0xa1,
	0xf2, 0x10, 0x8e, 0x56, 0x10, 0x17, 0x7b, 0x40, 0x51, 0x7e, 0x4a, 0x69, 0x72, 0x89, 0x90, 0x10,
	0x17, 0x1f, 0x94, 0x19, 0x9a, 0x97, 0x9d, 0x97, 0x5f, 0x9e, 0x27, 0xc0, 0x20, 0xc4, 0xcf, 0xc5,
	0x05, 0x15, 0xf3, 0xcf, 0x4b, 0x15, 0x78, 0xc1, 0x8e, 0x24, 0x10, 0x52, 0x9e, 0x2f, 0xf0, 0x92,
	0x5d, 0x48, 0x90, 0x8b, 0x07, 0x26, 0x90, 0x51, 0x94, 0x9a, 0x2a, 0xf0, 0x8a, 0xdd, 0xc8, 0x90,
	0x8b, 0xd5, 0x03, 0xe4, 0x52, 0x21, 0x0d, 0x2e, 0xe6, 0xe0, 0xc4, 0x4a, 0x21, 0x7e, 0x3d, 0x88,
	0x5b, 0xf5, 0xa0, 0x0e, 0x95, 0x12, 0x40, 0x08, 0x40, 0x1c, 0x97, 0xc4, 0x06, 0xf6, 0x94, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x22, 0x0c, 0xd4, 0xe3, 0x00, 0x00, 0x00,
}
